In [1]:
import pandas as pd

file_path = '../datasets/home-data-for-ml-course/train.csv'
home_data = pd.read_csv(file_path)

home_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [2]:
y = home_data.SalePrice

In [3]:
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = home_data[features]

In [4]:
X

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9
...,...,...,...,...,...,...,...
1455,7917,1999,953,694,2,3,7
1456,13175,1978,2073,0,2,3,7
1457,9042,1941,1188,1152,2,4,9
1458,9717,1950,1078,0,1,2,5
1459,9937,1965,1256,0,1,3,6

In [5]:
X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9

In [6]:
from sklearn.tree import DecisionTreeRegressor

# Specify a number for random_state to ensure same results each run
iowa_model = DecisionTreeRegressor(random_state=1)

# Fit model
iowa_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

In [7]:
predictions = iowa_model.predict(X)

In [8]:
from IPython.display import Markdown, display

report = f"""
### Results
Making predictions for the following 5 houses:
{X.head().to_markdown(index=False)}

The predictions are:
{y.head().to_markdown(index=False)}

{predictions[0:5]}
"""

display(Markdown(report))

### Results
Making predictions for the following 5 houses:
|   LotArea |   YearBuilt |   1stFlrSF |   2ndFlrSF |   FullBath |   BedroomAbvGr |   TotRmsAbvGrd |
|----------:|------------:|-----------:|-----------:|-----------:|---------------:|---------------:|
|      8450 |        2003 |        856 |        854 |          2 |              3 |              8 |
|      9600 |        1976 |       1262 |          0 |          2 |              3 |              6 |
|     11250 |        2001 |        920 |        866 |          2 |              3 |              6 |
|      9550 |        1915 |        961 |        756 |          1 |              3 |              7 |
|     14260 |        2000 |       1145 |       1053 |          2 |              4 |              9 |

The predictions are:
|   SalePrice |
|------------:|
|      208500 |
|      181500 |
|      223500 |
|      140000 |
|      250000 |

[208500. 181500. 223500. 140000. 250000.]