In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

# Load the data
file_path = '../datasets/home-data-for-ml-course/train.csv'
home_data = pd.read_csv(file_path)

# Select columns corresponding to features and target
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = home_data[features]
y = home_data.SalePrice

X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9

In [2]:
# Split into validation and training data
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=1)

# Define a random forest model
model = RandomForestRegressor(random_state=1)
model.fit(X_train, y_train)
pred_valid = model.predict(X_valid)
valid_mae = mean_absolute_error(y_valid, pred_valid)

print("Validation MAE for Random Forest Model: {:,.0f}".format(valid_mae))

Validation MAE for Random Forest Model: 21,857

In [3]:
# Create and fit a new model
model = RandomForestRegressor(max_leaf_nodes=100, random_state=1)
model.fit(X, y)

RandomForestRegressor(max_leaf_nodes=100, random_state=1)

In [4]:
# Load test data
file_path = '../datasets/home-data-for-ml-course/test.csv'
test_data = pd.read_csv(file_path)

# create X_test which comes from test_data but includes only the columns you used for prediction.
X_test = test_data[features]

# make predictions which we will submit. 
y_test = model.predict(X_test)

In [5]:
# Run the code to save predictions in the ".csv" format
output = pd.DataFrame({'Id': test_data.Id, 'SalePrice': y_test})
# output.to_csv('submission.csv', index=False)

In [16]:
from IPython.display import display, HTML, Markdown

predictions = pd.DataFrame(y_test, columns=['SalePrice'], dtype='float64')

report = f"""
<div style="display: flex;">
    <div style="border-right: #cecece 1px solid;">
        {X_test.to_html(index=False)}
    </div>
    <div style="background-color: #f0f3ff;">
        {predictions.to_html(index=False)}
    </div>
</div>
"""

display(Markdown(report))

<div style="display: flex;">
    <div style="border-right: #cecece 1px solid;">
        <table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>LotArea</th>
      <th>YearBuilt</th>
      <th>1stFlrSF</th>
      <th>2ndFlrSF</th>
      <th>FullBath</th>
      <th>BedroomAbvGr</th>
      <th>TotRmsAbvGrd</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>11622</td>
      <td>1961</td>
      <td>896</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>14267</td>
      <td>1958</td>
      <td>1329</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>13830</td>
      <td>1997</td>
      <td>928</td>
      <td>701</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9978</td>
      <td>1998</td>
      <td>926</td>
      <td>678</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>5005</td>
      <td>1992</td>
      <td>1280</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>10000</td>
      <td>1993</td>
      <td>763</td>
      <td>892</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>7980</td>
      <td>1992</td>
      <td>1187</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>8402</td>
      <td>1998</td>
      <td>789</td>
      <td>676</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>10176</td>
      <td>1990</td>
      <td>1341</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>8400</td>
      <td>1970</td>
      <td>882</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>5858</td>
      <td>1999</td>
      <td>1337</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>1680</td>
      <td>1971</td>
      <td>483</td>
      <td>504</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>1680</td>
      <td>1971</td>
      <td>525</td>
      <td>567</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>2280</td>
      <td>1975</td>
      <td>855</td>
      <td>601</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>2280</td>
      <td>1975</td>
      <td>836</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>12858</td>
      <td>2009</td>
      <td>1627</td>
      <td>707</td>
      <td>2</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>12883</td>
      <td>2009</td>
      <td>1544</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>11520</td>
      <td>2005</td>
      <td>1698</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>14122</td>
      <td>2005</td>
      <td>1822</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>14300</td>
      <td>2003</td>
      <td>2696</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>13650</td>
      <td>2002</td>
      <td>1687</td>
      <td>563</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>7132</td>
      <td>2006</td>
      <td>1370</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>18494</td>
      <td>2005</td>
      <td>1324</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>3203</td>
      <td>2006</td>
      <td>1145</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>13300</td>
      <td>2004</td>
      <td>744</td>
      <td>630</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>8577</td>
      <td>2004</td>
      <td>847</td>
      <td>886</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>17433</td>
      <td>1998</td>
      <td>1645</td>
      <td>830</td>
      <td>2</td>
      <td>4</td>
      <td>7</td>
    </tr>
    <tr>
      <td>8987</td>
      <td>2005</td>
      <td>1595</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9215</td>
      <td>2009</td>
      <td>1218</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>10440</td>
      <td>2005</td>
      <td>1468</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>11920</td>
      <td>2004</td>
      <td>831</td>
      <td>828</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>9800</td>
      <td>1920</td>
      <td>1012</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>15410</td>
      <td>1974</td>
      <td>1494</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>13143</td>
      <td>1993</td>
      <td>1251</td>
      <td>1098</td>
      <td>2</td>
      <td>4</td>
      <td>9</td>
    </tr>
    <tr>
      <td>11134</td>
      <td>1992</td>
      <td>1402</td>
      <td>823</td>
      <td>2</td>
      <td>4</td>
      <td>7</td>
    </tr>
    <tr>
      <td>4835</td>
      <td>2004</td>
      <td>1488</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>3515</td>
      <td>2004</td>
      <td>840</td>
      <td>840</td>
      <td>2</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <td>3215</td>
      <td>2004</td>
      <td>600</td>
      <td>600</td>
      <td>2</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>2544</td>
      <td>2004</td>
      <td>600</td>
      <td>600</td>
      <td>2</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>2544</td>
      <td>2005</td>
      <td>600</td>
      <td>636</td>
      <td>2</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>2980</td>
      <td>2000</td>
      <td>756</td>
      <td>756</td>
      <td>2</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>2403</td>
      <td>2003</td>
      <td>530</td>
      <td>550</td>
      <td>2</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>12853</td>
      <td>2010</td>
      <td>1418</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>6</td>
    </tr>
    <tr>
      <td>7379</td>
      <td>2000</td>
      <td>975</td>
      <td>873</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>8000</td>
      <td>2002</td>
      <td>1492</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>10456</td>
      <td>1967</td>
      <td>1829</td>
      <td>0</td>
      <td>2</td>
      <td>4</td>
      <td>8</td>
    </tr>
    <tr>
      <td>10791</td>
      <td>1993</td>
      <td>1280</td>
      <td>1215</td>
      <td>2</td>
      <td>4</td>
      <td>9</td>
    </tr>
    <tr>
      <td>18837</td>
      <td>1978</td>
      <td>1287</td>
      <td>604</td>
      <td>3</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>9600</td>
      <td>1971</td>
      <td>930</td>
      <td>715</td>
      <td>1</td>
      <td>4</td>
      <td>7</td>
    </tr>
    <tr>
      <td>9600</td>
      <td>1966</td>
      <td>1232</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9900</td>
      <td>1966</td>
      <td>1209</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9680</td>
      <td>1967</td>
      <td>1510</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>10600</td>
      <td>1964</td>
      <td>1131</td>
      <td>644</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>13260</td>
      <td>1962</td>
      <td>1728</td>
      <td>0</td>
      <td>2</td>
      <td>6</td>
      <td>10</td>
    </tr>
    <tr>
      <td>9724</td>
      <td>1952</td>
      <td>1929</td>
      <td>532</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>17360</td>
      <td>1949</td>
      <td>1019</td>
      <td>537</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>11380</td>
      <td>1966</td>
      <td>1128</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>8267</td>
      <td>1958</td>
      <td>1604</td>
      <td>0</td>
      <td>2</td>
      <td>4</td>
      <td>8</td>
    </tr>
    <tr>
      <td>8197</td>
      <td>2003</td>
      <td>1480</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>8050</td>
      <td>1959</td>
      <td>1143</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>10725</td>
      <td>1959</td>
      <td>1206</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>10032</td>
      <td>1959</td>
      <td>1580</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>8382</td>
      <td>1956</td>
      <td>832</td>
      <td>505</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>10950</td>
      <td>1952</td>
      <td>1064</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>10895</td>
      <td>1955</td>
      <td>972</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>13587</td>
      <td>1958</td>
      <td>988</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>7898</td>
      <td>1920</td>
      <td>985</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>8064</td>
      <td>1948</td>
      <td>816</td>
      <td>408</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>7635</td>
      <td>1960</td>
      <td>1175</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9760</td>
      <td>1963</td>
      <td>1395</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>7</td>
    </tr>
    <tr>
      <td>4800</td>
      <td>1900</td>
      <td>1157</td>
      <td>687</td>
      <td>1</td>
      <td>3</td>
      <td>9</td>
    </tr>
    <tr>
      <td>4485</td>
      <td>1920</td>
      <td>936</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>5805</td>
      <td>1957</td>
      <td>1347</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>6900</td>
      <td>1938</td>
      <td>827</td>
      <td>424</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>11851</td>
      <td>1948</td>
      <td>1027</td>
      <td>606</td>
      <td>1</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>8239</td>
      <td>1920</td>
      <td>1060</td>
      <td>185</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9656</td>
      <td>1923</td>
      <td>832</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>9600</td>
      <td>1900</td>
      <td>930</td>
      <td>636</td>
      <td>2</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>9000</td>
      <td>1890</td>
      <td>1157</td>
      <td>1111</td>
      <td>3</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>9045</td>
      <td>1910</td>
      <td>1128</td>
      <td>1128</td>
      <td>2</td>
      <td>4</td>
      <td>12</td>
    </tr>
    <tr>
      <td>10560</td>
      <td>1922</td>
      <td>868</td>
      <td>602</td>
      <td>1</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>5830</td>
      <td>1950</td>
      <td>1030</td>
      <td>582</td>
      <td>1</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>7793</td>
      <td>1922</td>
      <td>1160</td>
      <td>908</td>
      <td>1</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>5000</td>
      <td>1925</td>
      <td>765</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>6000</td>
      <td>1939</td>
      <td>608</td>
      <td>524</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>6000</td>
      <td>1940</td>
      <td>848</td>
      <td>348</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>6360</td>
      <td>1942</td>
      <td>955</td>
      <td>498</td>
      <td>1</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>6000</td>
      <td>1948</td>
      <td>780</td>
      <td>636</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>6240</td>
      <td>1936</td>
      <td>548</td>
      <td>492</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>6240</td>
      <td>1930</td>
      <td>928</td>
      <td>608</td>
      <td>2</td>
      <td>4</td>
      <td>7</td>
    </tr>
    <tr>
      <td>6120</td>
      <td>1923</td>
      <td>1068</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>8094</td>
      <td>1915</td>
      <td>888</td>
      <td>1074</td>
      <td>1</td>
      <td>4</td>
      <td>9</td>
    </tr>
    <tr>
      <td>12900</td>
      <td>1912</td>
      <td>780</td>
      <td>780</td>
      <td>1</td>
      <td>3</td>
      <td>7</td>
    </tr>
    <tr>
      <td>3068</td>
      <td>1920</td>
      <td>662</td>
      <td>662</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>15263</td>
      <td>1959</td>
      <td>1675</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>10632</td>
      <td>1917</td>
      <td>725</td>
      <td>499</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9900</td>
      <td>1915</td>
      <td>1212</td>
      <td>180</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>6001</td>
      <td>1940</td>
      <td>600</td>
      <td>319</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>6449</td>
      <td>1907</td>
      <td>942</td>
      <td>942</td>
      <td>1</td>
      <td>4</td>
      <td>7</td>
    </tr>
    <tr>
      <td>6048</td>
      <td>1910</td>
      <td>936</td>
      <td>744</td>
      <td>2</td>
      <td>2</td>
      <td>7</td>
    </tr>
    <tr>
      <td>10773</td>
      <td>1967</td>
      <td>1832</td>
      <td>0</td>
      <td>2</td>
      <td>4</td>
      <td>8</td>
    </tr>
    <tr>
      <td>7800</td>
      <td>1966</td>
      <td>892</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>7832</td>
      <td>1968</td>
      <td>864</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>7424</td>
      <td>1978</td>
      <td>1373</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>11227</td>
      <td>1968</td>
      <td>720</td>
      <td>720</td>
      <td>1</td>
      <td>4</td>
      <td>7</td>
    </tr>
    <tr>
      <td>20062</td>
      <td>1977</td>
      <td>1483</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>4</td>
    </tr>
    <tr>
      <td>9259</td>
      <td>1927</td>
      <td>756</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>17082</td>
      <td>1978</td>
      <td>1117</td>
      <td>864</td>
      <td>2</td>
      <td>4</td>
      <td>8</td>
    </tr>
    <tr>
      <td>18600</td>
      <td>1938</td>
      <td>1052</td>
      <td>558</td>
      <td>2</td>
      <td>4</td>
      <td>8</td>
    </tr>
    <tr>
      <td>11479</td>
      <td>1950</td>
      <td>1074</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9350</td>
      <td>1947</td>
      <td>1169</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>9525</td>
      <td>1954</td>
      <td>1172</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>17485</td>
      <td>2009</td>
      <td>1508</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>5</td>
    </tr>
    <tr>
      <td>11200</td>
      <td>1964</td>
      <td>1298</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>11980</td>
      <td>1987</td>
      <td>1433</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>4</td>
    </tr>
    <tr>
      <td>12361</td>
      <td>1993</td>
      <td>964</td>
      <td>838</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>7360</td>
      <td>2010</td>
      <td>1222</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>14235</td>
      <td>1900</td>
      <td>831</td>
      <td>614</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>11105</td>
      <td>1996</td>
      <td>965</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <td>9337</td>
      <td>1997</td>
      <td>892</td>
      <td>800</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>15240</td>
      <td>1977</td>
      <td>1026</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>7480</td>
      <td>1972</td>
      <td>876</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>10389</td>
      <td>2003</td>
      <td>1978</td>
      <td>0</td>
      <td>2</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <td>9375</td>
      <td>1997</td>
      <td>1044</td>
      <td>1054</td>
      <td>2</td>
      <td>4</td>
      <td>9</td>
    </tr>
    <tr>
      <td>4435</td>
      <td>2003</td>
      <td>848</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>4</td>
    </tr>
    <tr>
      <td>8777</td>
      <td>1945</td>
      <td>640</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>8842</td>
      <td>1954</td>
      <td>992</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>10044</td>
      <td>1968</td>
      <td>1196</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <td>11792</td>
      <td>1948</td>
      <td>792</td>
      <td>328</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>6305</td>
      <td>1975</td>
      <td>1096</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>6410</td>
      <td>1958</td>
      <td>960</td>
      <td>0</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <td>4853</td>
      <td>1924</td>
      <td>1296</td>
      <td>0</td>
      <td>2</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>7890</td>
      <td>1939</td>
      <td>856</td>
      <td>0</td>